### PR TITLE
feat: constraints on sources, deadlock prevention, and a faster FK lookup

### LINKED ISSUE #79: Performance issues while creating constraints with v1.x.x
Upgrading from v0.6.3 to any version >= v1.0.0 ended up with performance issues in constraint creation.

We're on dbt Cloud (versionless).
During my tests, I'd built same sample model using same source data.
Table creation time was always same, but there was a huge difference in time required to create constraints.
In the logs below, you can see that it took 3 mins to create a not null constraint on v1.0.0, whereas it used to be 1-2 seconds on v0.6.3.

**output with v1.0.0 (same with all v1 releases)**
```
....
....
09:56:23 Installing Snowflake-Labs/dbt_constraints
09:56:23 Installed from version 1.0.0
09:56:23 Updated version available: 1.0.3
....
....
....
09:58:11 Running dbt Constraints
09:58:12 Creating not null constraint for: <colum_name> in <model_name>
10:01:18 Creating unique key: <unique_key_name>
10:01:50 Finished dbt Constraints
10:01:50 5 of 5 START hook: dbt_constraints.on-run-end.0 ................................ [RUN]
10:01:50 5 of 5 OK hook: dbt_constraints.on-run-end.0 ................................... [OK in 0.00s]
....
....
```

**output with v0.6.3**
```
....
....
12:00:52 Installing Snowflake-Labs/dbt_constraints
12:00:52 Installed from version 0.6.3
12:00:52 Updated version available: 1.0.3
....
....
....
12:02:17 Running dbt Constraints
12:02:18 Creating not null constraint for: <colum_name> in <model_name>
12:02:19 Creating unique key: <unique_key_name>
12:02:21 Finished dbt Constraints
12:02:21 5 of 5 START hook: dbt_constraints.on-run-end.0 ................................ [RUN]
12:02:21 5 of 5 OK hook: dbt_constraints.on-run-end.0 ................................... [OK in 0.00s]
....
```

### LINKED ISSUE #100: UK Tests (and other tests presumably) Fail when a where clause predicate is specified
With the new changes in [#99](https://github.com/Snowflake-Labs/dbt_constraints/pull/99) any tests which include a where clause predicate is failing.

Take, for example, this test configuration:

```
- dbt_constraints.unique_key:
        column_names: 
          - field_1
          - field_2
          - field_3
        where: field_1 is not null and field_4 = 'ACTIVE'
```

The issue is that the test query is generated per the dbt documentation to include a filtered record subset like so:

```
    select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
      
    
  select validation_errors.* from (
    select
        uk_test.field_1, uk_test.field_2, uk_test.field_3, count(*) as n_records
    from (select * from database.dbt_cloud_pr_1234_1.table_1 where field_1 is not null and field_4 = 'SOMETHING') dbt_subquery uk_test
    group by uk_test.field_1, uk_test.field_2, uk_test.field_3
    having count(*) > 1
) validation_errors
  
  
      
    ) dbt_internal_test
```

I believe this can be solved by ensuring that the dbt subquery is wrapped in a set of parens with an additional `select *`: `select * from ([dbt provided table name or subquery]) uk_test`. In the base case without a subquery I believe this would also work as expected.

### LINKED ISSUE #119: 'config: where:' causes invalid sql due to double alias ' dbt_subquery fk_child_inner'
# Issue
When trying to apply conditional logic to a test config the package compiles invalid sql statements. 

I've been searching for related issues and #98 looks quite similar. 

Running: 
```
dbt_constraints v1.0.8
dbt-core==1.11.8
dbt-snowflake==1.11.4
```

To replicate
**fct_test.sql** & **dim_test.sql** (identical files for test purpose)
```sql
{{ config(
    materialized='table',
    tags=['test']
) }}
select '2024-06-01'::date as date_key
```

**test.yml**
```yml
version: 2

models:
  - name: fct_test
    columns:
      - name: date_key
        tests:
          - dbt_constraints.foreign_key:
              arguments:
                pk_table_name: ref('dim_test')
                pk_column_name: date_key
              config:
                where: "1 = 2"  # Adding this will cause the issue
```

When omitting the `config: where: ` part the build is successful. When enabled it will compile it into this:
```sql
  select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
select validation_errors.* from (
    select
        fk_child.*
    from (
        select
            fk_child_inner.date_key
        from (select * from test_db.dbt.fct_test where 1 = 2) dbt_subquery fk_child_inner
        where 1=1
            and fk_child_inner.date_key is not null
            ) fk_child
    left join (
        select
            fk_parent_inner.date_key
        from test_db.dbt.dim_test fk_parent_inner
        ) fk_parent
            on fk_child.date_key = fk_parent.date_key
    where fk_parent.date_key is null
) validation_errors
    ) dbt_internal_test
```

The problem being the line with `from (select * from test_db.dbt.fct_test where 1 = 2) dbt_subquery fk_child_inner` creating 2 aliasses.

### LINKED ISSUE #130: dbt 1.12 reports invalid `quote_columns` macro annotation
After upgrading from dbt Core 1.11 to 1.12, dbt commands fail while parsing `dbt_constraints` 1.0.9.

## Error

```text
Compilation Error
  [WARNING]: Argument quote_columns in the yaml for macro create_constraints has an invalid type.
```

## Environment

- dbt-core 1.12.0
- dbt-postgres 1.11.0
- dbt_constraints 1.0.9
- All warnings are treated as errors with `warn_error_options.error: all`

It looks like the package declares the argument as:

```yaml
- name: quote_columns
  type: boolean
```

dbt 1.12 accepts `bool` as the macro argument type instead of `boolean`.
There also seem to be a few other macro annotation/signature warnings in the package.

For now, we have pinned dbt Core below 1.12 and dbt-postgres below 1.11. Would it be possible to update the macro annotations for dbt 1.12 compatibility?

### LINKED ISSUE #131: Constraints skipped as "insufficient privileges" — meta.materialized default forces verify_permissions=true for all models (regression since 1.0.8)
## Summary

Since **1.0.8**, the `on-run-end` constraint hook skips **all** constraints on Snowflake with `…because of insufficient privileges`, even when the dbt run role **owns** the tables. The root cause is a `verify_permissions` gate in `create_constraints.sql` that evaluates `true` for essentially every model because of a `meta.materialized` default, which turns on an ownership pre-check that is unreliable for freshly `CREATE OR REPLACE`d tables.

Constraints were created normally on **1.0.4–1.0.7**; upgrading to **1.0.9** (and 1.0.8) broke them with no other change.

## Environment

- Package: `Snowflake-Labs/dbt_constraints` **1.0.9** (regression also present in 1.0.8)
- Adapter: `dbt-snowflake` (dbt Core)
- Models: transient tables built via `create or replace transient table …` (`table` / `incremental` materializations)
- The run role owns the models (confirmed via `SHOW GRANTS ON TABLE …` → `OWNERSHIP`)

## Symptom

For every model, the hook logs:

```text
Skipping not null constraint for <col> in <db>.<schema>.<table> because of insufficient privileges: <db>.<schema>.<table>
Skipping <TABLE>_..._PK because of insufficient privileges: <db>.<schema>.<table>
```

The skip is entirely client-side — no `ALTER … ADD CONSTRAINT` or `SHOW GRANTS` is ever submitted (verified in Snowflake `QUERY_HISTORY`).

## Root cause

In `macros/create_constraints.sql` (main), `verify_permissions` is set here:

```jinja
{# lines 394-398 #}
{%- if node.resource_type == "source"
    or node.config.get("materialized", "other") not in ("table", "incremental", "snapshot", "seed")
    or node.config.get("meta", {}).get("materialized", "other") not in ("table", "incremental", "snapshot", "seed") -%}
    {%- set ns.verify_permissions = true -%}
{%- endif -%}
```

The third clause (added in 1.0.8) reads `node.config.meta.materialized`, which is almost never set and therefore defaults to `"other"`. Because `"other"` is never in `("table","incremental","snapshot","seed")`, **this clause is always true**, so `verify_permissions` becomes `true` for **every** model — including ordinary `table`/`incremental` models that the first two clauses intentionally leave `false`.

With `verify_permissions=true`, `snowflake__have_ownership_priv` (`macros/snowflake__create_constraints.sql:367`) runs the privilege check:

```jinja
{%- if verify_permissions is sameas true -%}
  {%- set table_privileges = dbt_constraints.lookup_table_privileges(table_relation, lookup_cache) -%}
  {%- if "OWNERSHIP" in table_privileges -%}
    {{ return(true) }}
  {%- else -%}
    {{ return(false) }}
```

`lookup_table_privileges` sources this from `INFORMATION_SCHEMA.TABLE_PRIVILEGES` (`… and tp.privilege_type in ('OWNERSHIP', 'REFERENCES')`, line 396). For a table that was just `CREATE OR REPLACE`d earlier in the same run (normal for transient dbt models), that view does **not** reliably surface the `OWNERSHIP` row at `on-run-end` time, so `have_ownership_priv` returns `false` and every constraint is skipped — even though `SHOW GRANTS ON TABLE` confirms the run role owns it.

Before 1.0.8, `verify_permissions` stayed `false` for `table`/`incremental` models, so `have_ownership_priv` short-circuited to `return(true)` and constraints were always created.

## Expected behavior

`verify_permissions` should only be forced `true` for materializations that genuinely need a privilege check (sources / custom materializations) — not for every model because an unset `meta.materialized` defaults to `"other"`.

## Suggested fix

Guard the meta clause so it only applies when `meta.materialized` is explicitly set:

```jinja
or ( node.config.get("meta", {}).get("materialized") is not none
     and node.config.get("meta", {}).get("materialized") not in ("table", "incremental", "snapshot", "seed") )
```

The analogous `meta.materialized` clause in the node-selection filter (lines 368–369) has the same defaulting behavior and likely needs the same guard.

## Additional note

Independent of the gate bug, having `have_ownership_priv` depend on `INFORMATION_SCHEMA.TABLE_PRIVILEGES` reporting `OWNERSHIP` is fragile for freshly replaced tables — that view lags for the newly-created object, while `SHOW GRANTS ON TABLE` is authoritative and immediate. This is the same class of metadata-view unreliability noted in #42.

### LINKED ISSUE #132: Performance issue with dbt 1.12
Hi there!

After upgrading dbt-core from 1.11 to 1.12, dbt-constraints post-hook runtime increased significantly:

dbt 1.11
16:43:48  2 of 2 START hook: dbt_constraints.on-run-end.1 ................................ [RUN]
16:43:48  2 of 2 OK hook: dbt_constraints.on-run-end.1 ................................... [OK in 0.70s]

dbt 1.12
16:42:29  2 of 2 START hook: dbt_constraints.on-run-end.1 ................................ [RUN]
16:42:29  2 of 2 OK hook: dbt_constraints.on-run-end.1 ................................... [OK in 19.12s]

Probably related to https://github.com/Snowflake-Labs/dbt_constraints/issues/79

### PR DESCRIPTION
**Pull request by sfc-gh-dflippo**
Three changes to the package, three regression fixes, and the test work needed
to prove them.

Closes #79, closes #100, closes #119, closes #130, closes #131, closes #132.

## Faster FK lookup (@RichardGoerlerKS, #128)

This commit is @RichardGoerlerKS's work from #128, carried here so it ships with 1.0.9.
`test_selected` was called once per test, and each call looped over every node in the
graph to find the unique and primary keys on models that a selected model's foreign keys
point at. That is O(n squared) and it hurt on large projects. The FK model list is now
built once per `create_constraints_by_type` call and reused, so `test_selected` does a dict
lookup instead of a graph traversal.

## No constraints are created at all since 1.0.8 (#131)

Two clauses in `create_constraints_by_type` read `meta.materialized` with a literal
default of `"other"`. Almost no node sets that property, so both clauses read
`"other"`, which is in neither tuple they test, so both were always true.

That produced two faults. `verify_permissions` became true for every model, so the
ownership pre-check ran before every constraint. That check does not reliably report
OWNERSHIP for a table the same run just replaced, so the package skipped the
constraint. That is the reported symptom: no constraints at all, on a package whose
only job is to create them. It ships in the published 1.0.8.

The second fault is the reverse. The clause that excludes views, ephemeral models and
dynamic tables sits in an `or` inside an inclusive filter, so an always-true operand
made the exclusion dead and those nodes passed.

`meta.materialized` is an override, not an independent property: a custom
materialization uses it to declare the kind of object it builds. The new
`effective_materialization` macro reads it first and falls back to
`config.materialized`, and both call sites share that one definition.

This one is not reproducible from a build in a test account. dbt owns every table
there, so the pre-check passes and the constraints appear whether or not the bug is
present. A build assertion would pass before and after the fix and prove nothing. The
`assert_effective_materialization` operation instead calls the macro with synthetic
nodes and checks both decisions derived from it, across 12 cases. It fails on the
unfixed macro.

## The where config produced invalid SQL (#100, #119)

One root cause behind both issues. dbt replaces the model with
`(select * from x where ...) dbt_subquery` when a test sets the `where` config, and
that text already carries an alias. The test SQL read `from {{model}} pk_test`, so the
result held two aliases and the database rejected it with a syntax error at the
package's own alias. #100 is a regression from 1.0.6.

The test SQL now selects from the model through a subselect, so the test supplies the
only alias at its own level. The parent relation in the foreign key test is left
alone, because the `where` config never rewrites it.

## dbt 1.12 rejects the macro argument metadata (#130)

`macros.yml` used the type `boolean`, which is not in the accepted grammar, and five
macros documented fewer arguments than they declare and in a different order. dbt 1.12
validates all of that and fails the parse outright when `warn_error_options` sets
`error: all`, so the package could not be used with dbt 1.12 at all.

Types are corrected to `bool`, and `verify_permissions`, `lookup_cache` and
`rely_clause` are now documented in declaration order. Verified with a clean
`dbt parse` on dbt-core 1.12.3.

## Constraints declared on sources now actually get created

The source variables the README documents had no effect. Test dependencies were resolved
against `graph.nodes`, but dbt keeps sources in `graph.sources`, so every source dependency
resolved to nothing and no DDL was ever issued.

Dependencies now resolve from `graph.nodes` and fall back to `graph.sources`. A test on a
source also has no `attached_node`, so the package accepts a test depending on exactly one
node and reads the table name from `identifier`, which is where a source keeps it.

This is a behaviour change for anyone already running
`dbt_constraints_sources_enabled: true` — the package will start issuing DDL against their
source tables on the next run. The README now has a callout telling them to confirm the dbt
role should be altering those tables before upgrading.

## Deadlocks on databases that enforce constraints

Postgres and Oracle deadlocked under a parallel run. Dropping a constraint with CASCADE
also locks every table whose foreign key depends on it, and `drop_relation` was doing that
on each worker thread, so two threads could take the same locks in opposite order. The
existing mitigation was itself one of the deadlock participants.

Ordering can't fix this. None of the foreign keys in the integration project are backed by
a `ref()` in the child model, so dbt has no ordering guarantee between two models a foreign
key joins.

So the fix is timing. `relations_to_rebuild()` returns the relations the run will drop or
replace, and an `on-run-start` hook releases their constraints from a single session before
the threads start. Same DDL, same constraints, just one session and a different moment.
Seeds are always included, because a seed without a full refresh gets TRUNCATEd, which
needs the constraints gone just as much as a drop does.

Adapters opt in by implementing `release_constraints_for_rebuild`; the default does
nothing, so Snowflake and other non-enforcing databases are unaffected. Set
`dbt_constraints_release_before_build: false` to go back to dropping during the build.

Verified at 64 threads: postgres 25 passed with no deadlocks, oracle 23 passed with no
ORA-00060.

## Versioned-model name resolution in the pre-build release

`relations_to_rebuild()` used `node.alias or node.name` as the identifier, which is the
unversioned form. Constraint creation already resolves the physical name by reading
`node.relation_name` or appending `_v<version>`. Without the same resolution, the pre-build
constraint release targets the wrong table name for versioned models, so PostgreSQL and
Oracle could deadlock when threads rebuild tables that still have live foreign keys.

The same three-step version resolution from the constraint-creation path is now applied in
`relations_to_rebuild()` so both code paths agree on the physical identifier.

## Test bench

Two new matrix cells, `dpos_core` (dbt Core 1.11.11) and `dpos_fusion` (Fusion
2.0.0-preview.186), run dbt inside Snowflake against a deployed DBT PROJECT object rather
than a local client. Those are the versions `SYSTEM$SUPPORTED_DBT_VERSIONS()` returns. Host
cells are unchanged: `snowflake` 1.5.12 as the backward-compat floor, `fusion` 2.0.0rc212,
`core2` 2.0.0b2.

`dpos_stage.py` builds a deployable copy of the project. Snowflake rejects a package path
that leaves the project root, so `- local: ../../` won't deploy; the stage copies the repo
into `local_packages/`, rewrites `packages.yml`, and runs `dbt deps` so `dbt_packages/`
ships inside the object. That also avoids needing an external access integration.
`dpos_runner.py` maps harness commands onto `snow dbt execute` and handles the gaps: no
`dbt clean` or `dbt debug`, `deps` does nothing against a deployed object, a few flags are
rejected. `snow` is a subprocess too, so both paths return a `CompletedProcess` and the
assertions don't care which ran. Connection details live in `dbt_projects_profiles.yml` and
`env.yml`, filenames dbt ignores, so the local `profiles.yml` workflow is unaffected.

Every dbt invocation costs more than the work it does, and an in-database one pays for a
CLI start, a dbt start inside Snowflake, and a full parse first. A shared `baseline_build`
fixture exposes the session's single full build, and tests that just check "the package
created constraint X" read that log instead of rebuilding a model to grep it. Cells dropped
from ~50 invocations to 8; postgres went from ~18 minutes to just over one.

Three assertion bugs fell out of that. Assertions now match the whole
`creating <kind>: <name>` line, since the package also logs `Skipping <name> because ...`
and a bare name check couldn't tell those apart in either direction. They name the specific
constraint instead of a bare word like `primary_key`, which any model in a shared log would
satisfy. And `"NORELY"` contains `"RELY"`, so rely assertions match the full line including
the constraint name.

For coverage of the source and issue #110 work: source constraint tests in both projects, a
staging macro that pre-creates a constraint so the package sees an existing one, and
prestaged RELY, NORELY and alternate-name models. Issue #110 only applies when the
constraint already exists, so a post-hook creates it with the opposite rely flag and the
package has to correct it during `on-run-end`. That covers both directions plus the
hand-named case, which had no test before.

The two test projects are now chosen by dbt version rather than by engine.
`integration_tests/dbt-core` becomes `dbt-legacy-syntax` and
`integration_tests/dbt-fusion` becomes `dbt-current-syntax`, because the split follows
the `schema.yml` syntax, not the engine. dbt-core added the `arguments:` property for
generic tests in 1.10.5, so every cell at that version or later now runs the
current-syntax project, and recent dbt-core 1.x runs the same tests as dbt 2.x and
Fusion. Only `snowflake` 1.5.12 still runs the legacy project, which is what keeps the
older syntax covered. Verified that dbt-core 1.10.5 parses the current-syntax project,
including its `require_generic_test_arguments_property` flag.

The current-syntax project had drifted while it served Snowflake alone, and it now
runs against PostgreSQL and Oracle too, so it needed bringing back to parity:
`drop_cloned_tables` and the `on-run-start` hook that calls it were missing, which is
what keeps concurrent `drop ... cascade` statements from deadlocking PostgreSQL;
`macros/query.sql` was absent, and the harness calls it for the oracle cell; and three
duplicate foreign key declarations that prove the package does not create a constraint
twice were gone. `dbt ls` now reports no test present in one project and missing from
the other.

Both in-database cells stage from the current-syntax project now, and `env.yml` named
a single cell and schema, so they would have shared `dbt_constraints_dpos_fusion` and
overwritten each other. `env.yml` declares one environment per cell, and
`stage_project` sets `default_environment` while it stages.

Finally, sqlserver is out of the matrix. The package implements bigquery, oracle, postgres,
redshift, snowflake and vertica; there's no `sqlserver__create_constraints` and no
`default__`, so a sqlserver run dies at macro dispatch in the seed's `on-run-end` hook. The
cell could never have passed. `TESTING.md` called SQL Server experimental, which was
generous.

## Test plan

Final E2E run against current HEAD (`0375b97`), all seven cells run serially,
0 failures across the full matrix:

| Cell | dbt version | Passed | Skipped | Time |
|------|------------|--------|---------|------|
| postgres | 1.11.14 | 27 | 16 | 1m 41s |
| oracle | 1.12.3 | 25 | 18 | 3m 41s |
| snowflake | 1.5.12 | 37 | 6 | 7m 40s |
| fusion | 2.0.0rc212 | 39 | 4 | 5m 16s |
| core2 | 2.0.0b2 | 36 | 7 | 5m 02s |
| dpos_core | 1.11.11 | 37 | 6 | 9m 02s |
| dpos_fusion | preview.186 | 37 | 6 | 6m 54s |
| **Total** | | **238** | **63** | **39m 16s** |

Plus the 64-thread deadlock runs reported above.

I checked constraints in `INFORMATION_SCHEMA.TABLE_CONSTRAINTS` for the in-database schemas
rather than trusting the log, and diffed the staged package against the working tree to
confirm the cells test local edits and not a published release.

Cells have to run one at a time. Two separate collisions, both written up in
`integration_tests/AGENTS.md`: cells sharing a project directory clobber each other because
session prep runs `dbt clean` and deletes `dbt_packages` under a running cell, and every
Snowflake-targeting cell builds the issue_105 models into the shared `custom_db` /
`test_schema_<env>`, which aren't scoped per cell.

Use `python3 -m pytest` rather than bare `pytest` — `automated_tests/` has an `__init__.py`,
so pytest puts the parent on `sys.path` and `import dbt_venv` fails. The in-database cells
also need `SNOWFLAKE_CONNECTION_NAME` in `integration_tests/.env`, pointing at a
`connections.toml` entry for the same account as the `SNOWFLAKE_*` values. There's no
default on purpose, because a default would deploy to whatever account `connections.toml`
marks as `default`.

## Notes for review

Two Core-vs-Fusion differences showed up and both were test determinism, not package bugs.

`dim_part_supplier.ps_suppkey` had two `relationships` tests, one to a source and one to a
seed. Constraint names come from the child table and child columns only, so both produced
`DIM_PART_SUPPLIER_PS_SUPPKEY_FK`; the package created whichever came first and correctly
skipped the other, and the engines iterate in different orders. I moved the seed FK to
`ps_partkey`, so both get created on both engines.

`assert_fk_parity` was running in every build, but constraints are created in `on-run-end`,
after tests. It's now variable-gated and selected in the same `dbt test` call as
`assert_source_constraints`, so it costs no extra invocation.

## Commits

`d25414c` is by @RichardGoerlerKS, from #128. `9a58534` is the deadlock fix,
`1fe2395` the source constraints, `916124c` / `98de612` / `e3131df` are the #131, #100
and #130 fixes, `2aa4125` is the test project split, `913a822` the documentation,
`0375b97` is the versioned-model fix for `relations_to_rebuild()`, and the rest are
the test bench and housekeeping.

If #128 is merged first, drop `d25414c` from this branch and rebase.

### CODE REVIEW

**Review by sfc-gh-dflippo — COMMENTED** [review]
Reviewed and approved

**Review by sfc-gh-evenlet — APPROVED** [review]
Additional commit was done to fix some outstanding issues. PR approved

**Comment by afranzi** [comment]
Yes, please let's move forward with the fix release.
