### ISSUE TITLE
Latest version 0.6.0 working on dbt-snowflake 1.4.1 (core version 1.4.5

### ISSUE THREAD

**Issue by BI-MarcB** [Snowflake-Labs/dbt_constraints#46]
Hi,

When running on version 0.6.0 with dbt-snowflake 1.4.1 (which is core version 1.4.5), I get the following error:

**dbt build -s departure_source_market**
12:35:16  Running with dbt=1.4.5
12:35:17  Encountered an error:
**Compilation Error
  dbt found two macros named "test_primary_key" in the project
  "dbt_constraints".
   To fix this error, rename or remove one of the following macros:
      - macros\create_constraints.sql
      - macros\create_constraints.sql**

After downgrading to 0.5.3, it works again:
**dbt deps**
12:38:21  Running with dbt=1.4.5
12:38:22  Installing Snowflake-Labs/dbt_constraints
12:38:23    Installed from version 0.5.3
12:38:23    Updated version available: 0.6.0
12:38:23
12:38:23  Updates available for packages: ['Snowflake-Labs/dbt_constraints']
Update your versions in packages.yml, then run dbt deps

**dbt build -s departure_source_market**
12:38:34  Running with dbt=1.4.5
[...]
12:38:49  Running 1 on-run-end hook
12:38:49  Running dbt Constraints
12:38:49  Finished dbt Constraints
12:38:49  1 of 1 START hook: dbt_constraints.on-run-end.0 ................................ [RUN]
12:38:49  1 of 1 OK hook: dbt_constraints.on-run-end.0 ................................... [OK in 0.00s]

Could you take a look please?

**Comment by sfc-gh-dflippo** [comment]
Just to verify, after you switched to dbt-snowflake 1.4.1, did you run dbt clean, dbt deps, dbt build? I ran the following test with my integration test and had no errors:
```
pip install -U dbt-snowflake==1.4.1 dbt-postgres dbt-core
dbt clean
dbt deps
dbt build
```

**Comment by BI-MarcB** [comment]
Thanks for your quick reply. I cannot replicate the behaviour anymore. Running dbt clean, dbt deps and building the model works just fine with 0.6.0. I do not know what the initial problem was, but this issue can be closed.
